Models/Model1.Context.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Uyegirisuygulama.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class UyelikEntities : DbContext
    {
        public UyelikEntities()
            : base("name=UyelikEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Kullanicilar> Kullanicilar { get; set; }
    }
}

Models/Model1.Designer.cs
// T4 code generation is enabled for model 'C:\Users\CingozR\documents\visual studio 2013\Projects\Uyegirisuygulama\Uyegirisuygulama\Models\Model1.edmx'. 
// To enable legacy code generation, change the value of the 'Code Generation Strategy' designer
// property to 'Legacy ObjectContext'. This property is available in the Properties Window when the model
// is open in the designer.

// If no context and entity classes have been generated, it may be because you created an empty model but
// have not yet chosen which version of Entity Framework to use. To generate a context class and entity
// classes for your model, open the model in the designer, right-click on the designer surface, and
// select 'Update Model from Database...', 'Generate Database from Model...', or 'Add Code Generation
// Item...'.

Models/Model1.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Uyegirisuygulama.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Controllers/UyeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Uyegirisuygulama.Models;

namespace Uyegirisuygulama.Controllers
{
    public class UyeController : Controller
    {
        //
        // GET: /Uye/
        [HttpGet]
        public ActionResult Giris()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Giris(Kullanicilar Kul)
        {
            if (ModelState.IsValid)
            {
                using (UyelikEntities DB = new UyelikEntities())
                {
                    var Uyegirisi = DB.Kullanicilar.Where(U => U.Kul_AD.Equals(U.Kul_AD) && U.Kul_PAROLA.Equals(U.Kul_PAROLA)).FirstOrDefault();
                    if (Uyegirisi != null)
                    {
                        Session["GirisKullaniciID"] = Uyegirisi.Kul_ID.ToString();
                        Session["GirisKullaniciAD"] = Uyegirisi.Kul_AD.ToString();
                        return RedirectToAction("Profil");
                    }
                }
                
            }
            return View(Kul);
        }

        public ActionResult Profil()
        {
            if (Session["GirisKullaniciID"] != null)
            {
                return View();
            }
            else
            {
                return RedirectToAction("Index");
            }
        }


	}
}

Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="http://asp.net" class="btn btn-primary btn-large">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", null, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Views/Uye/Giris.cshtml
@model Uyegirisuygulama.Models.Kullanicilar
@{
    ViewBag.Title = "Giris";
}

<h2>Giris</h2>

@using (Html.BeginForm("Giris","Uye",FormMethod.Post))
{
    @Html.AntiForgeryToken() // CSRF Saldırısını Önlemek İçin
    @Html.ValidationSummary(true)
    if (ViewBag.Mesaj!=null)
	{
    <div style="border: 1px solid red">
        @ViewBag.Mesaj
    </div>
    }
    <table>
        <tr>
            <td>@Html.LabelFor(x=> x.Kul_AD,"Kullanici Adınız: ")</td>
            <td>@Html.TextBoxFor(x=>x.Kul_AD)</td>
            <td>@Html.ValidationMessageFor(x=>x.Kul_AD)</td>
        </tr>
        <tr>
            <td>@Html.LabelFor(x => x.Kul_PAROLA, "Parola: ")</td>
            <td>@Html.PasswordFor(x=>x.Kul_PAROLA)</td>
            <td>@Html.ValidationMessageFor(x=>x.Kul_PAROLA)</td>
        </tr>
        <tr>
            <td></td>
            <td>
                <input type="submit" value="Giriş Yap" />
            </td>
            <td></td>
        </tr>
    </table>
}

Views/Uye/Profil.cshtml

@{
    ViewBag.Title = "Profil";
}


<h2>PROFİLİNİZ</h2>
@if (Session["GirisKullaniciAD"] != null)
{
    <text>
        <mark>Hoşgeldin</mark> <h2>@Session["GirisKullaniciAD"].ToString() </h2>
    </text>
}